//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebID_T
    {
        public int Entry_ID { get; set; }
        public string URL { get; set; }
        public string Contents_VC { get; set; }
        public Nullable<System.DateTime> DateAccessed_DT { get; set; }
    }
}
