//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_T
    {
        public int Error_ID { get; set; }
        public Nullable<System.DateTime> DateCreated_DT { get; set; }
        public string Message_VC { get; set; }
        public string ExceptionThrower_VC { get; set; }
    }
}
