//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL_T
    {
        public string URL { get; set; }
        public Nullable<long> Web_ID { get; set; }
        public Nullable<System.DateTime> Date_Accessed { get; set; }
        public string TextContent { get; set; }
    }
}
