<?xml version="1.0" encoding="utf-8"?><Database Name="ClaimStakerDEV" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=APEXEDI-DEV\APEXEDIDEV;Initial Catalog=ClaimStakerDEV;Persist Security Info=True;User ID=dariantest" SettingsObjectName="DatabaseConnection.Properties.Settings" SettingsPropertyName="ClaimStakerDEVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tests" Member="Tests">
    <Type Name="Test">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DateCreated_DT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Message_VC" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ExceptionThrower_VC" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>