<?xml version="1.0" encoding="utf-8"?><Database Name="Test" Class="DataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=EVERETT-PC\EVERETTSQL;Initial Catalog=Test;Integrated Security=True" SettingsObjectName="DatabaseConnection.Properties.Settings" SettingsPropertyName="TestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="User_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="UserName_VC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserInfo_T" Member="UserInfo_Ts">
    <Type Name="UserInfo_T">
      <Column Name="OrderID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserFirstName_VC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserLastName_VC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateJoined_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address_VC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="UserInfo_T_UserInfo_T" Member="UserInfo_T2" ThisKey="UserID" OtherKey="UserID" Type="UserInfo_T" Cardinality="One" />
      <Association Name="UserInfo_T_UserInfo_T1" Member="UserInfo_T4" ThisKey="UserID" OtherKey="UserID" Type="UserInfo_T" Cardinality="One" />
      <Association Name="UserInfo_T_UserInfo_T" Member="UserInfo_T1" ThisKey="UserID" OtherKey="UserID" Type="UserInfo_T" IsForeignKey="true" />
      <Association Name="UserInfo_T_UserInfo_T1" Member="UserInfo_T3" ThisKey="UserID" OtherKey="UserID" Type="UserInfo_T" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order_T" Member="Order_Ts">
    <Type Name="Order_T">
      <Column Name="OrderID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderName_VC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OrderDate_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>